CREATE DATABASE IF NOT EXISTS teste_api CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE teste_api;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(40) DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  cep VARCHAR(9) DEFAULT NULL,
  street VARCHAR(255) DEFAULT NULL,
  neighborhood VARCHAR(255) DEFAULT NULL,
  city VARCHAR(120) DEFAULT NULL,
  state VARCHAR(2) DEFAULT NULL,
  complement VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE users ADD COLUMN IF NOT EXISTS cep VARCHAR(9) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS street VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR(120) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS state VARCHAR(2) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS complement VARCHAR(255) DEFAULT NULL;
